// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const user = {
        id: "demo-" + provider + "-user",
        email: `${provider}.user@uccnowondemand.com`,
        user_metadata: { display_name: `${provider.charAt(0).toUpperCase() + provider.slice(1)} User` }
      };
      if (typeof window !== 'undefined') {
        localStorage.setItem('ucc_now_demo_session', JSON.stringify(user));
      }
      return { redirected: false, error: null };
    },
  },
};
