// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

const listeners: Array<(event: string, session: any) => void> = [];

function getDemoUsers() {
  if (typeof window === 'undefined') return [];
  const stored = localStorage.getItem('ucc_now_demo_users');
  if (stored) {
    try {
      return JSON.parse(stored);
    } catch (e) {
      // ignore
    }
  }
  const defaultUsers = [
    { email: 'admin@uccnowondemand.com', password: 'Admin@321', name: 'Admin' }
  ];
  localStorage.setItem('ucc_now_demo_users', JSON.stringify(defaultUsers));
  return defaultUsers;
}

const mockAuth = {
  async getUser() {
    const sessionStr = typeof window !== 'undefined' ? localStorage.getItem('ucc_now_demo_session') : null;
    if (sessionStr) {
      return { data: { user: JSON.parse(sessionStr) }, error: null };
    }
    return { data: { user: null }, error: { message: "No active user" } };
  },
  async getSession() {
    const sessionStr = typeof window !== 'undefined' ? localStorage.getItem('ucc_now_demo_session') : null;
    if (sessionStr) {
      const user = JSON.parse(sessionStr);
      return { data: { session: { user, access_token: "demo-token" } }, error: null };
    }
    return { data: { session: null }, error: null };
  },
  async signInWithPassword({ email, password }: any) {
    const users = getDemoUsers();
    const match = users.find((u: any) => u.email.toLowerCase() === email.toLowerCase() && u.password === password);
    if (match) {
      const user = {
        id: "demo-user-" + match.email.replace(/[^a-zA-Z0-9]/g, ''),
        email: match.email,
        user_metadata: { display_name: match.name }
      };
      if (typeof window !== 'undefined') {
        localStorage.setItem('ucc_now_demo_session', JSON.stringify(user));
      }
      listeners.forEach(cb => cb("SIGNED_IN", { user }));
      return { data: { user }, error: null };
    }
    return { data: { user: null }, error: { message: "Invalid credentials. Use admin@uccnowondemand.com / Admin@321, or sign up." } };
  },
  async signUp({ email, password, options }: any) {
    const users = getDemoUsers();
    const exists = users.some((u: any) => u.email.toLowerCase() === email.toLowerCase());
    if (exists) {
      return { data: { user: null }, error: { message: "User already exists." } };
    }
    const name = options?.data?.display_name || email.split('@')[0];
    const newUser = { email, password, name };
    users.push(newUser);
    if (typeof window !== 'undefined') {
      localStorage.setItem('ucc_now_demo_users', JSON.stringify(users));
    }
    const user = {
      id: "demo-user-" + email.replace(/[^a-zA-Z0-9]/g, ''),
      email,
      user_metadata: { display_name: name }
    };
    if (typeof window !== 'undefined') {
      localStorage.setItem('ucc_now_demo_session', JSON.stringify(user));
    }
    listeners.forEach(cb => cb("SIGNED_IN", { user }));
    return { data: { user }, error: null };
  },
  async signOut() {
    if (typeof window !== 'undefined') {
      localStorage.removeItem('ucc_now_demo_session');
    }
    listeners.forEach(cb => cb("SIGNED_OUT", null));
    return { error: null };
  },
  async setSession(tokens: any) {
    return { data: { session: null }, error: null };
  },
  onAuthStateChange(callback: any) {
    listeners.push(callback);
    const sessionStr = typeof window !== 'undefined' ? localStorage.getItem('ucc_now_demo_session') : null;
    if (sessionStr) {
      const user = JSON.parse(sessionStr);
      callback("SIGNED_IN", { user });
    } else {
      callback("SIGNED_OUT", null);
    }
    return {
      data: {
        subscription: {
          unsubscribe() {
            const idx = listeners.indexOf(callback);
            if (idx !== -1) listeners.splice(idx, 1);
          }
        }
      }
    };
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(target, prop, receiver) {
    if (prop === 'auth') {
      return mockAuth;
    }
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});


